apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  labels:
    env: test
spec:
  template:
    
    metadata:
      name: nginx1
      labels:
        env: test
    spec:
      containers:
        - name: nginx1-container
          image: nginx
  
  replicas: 2
  selector:
    matchLabels:
      env: test

